### ISSUE TITLE
code-ป้งกันการขโมยการ์ด

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/project#12]

**Comment by JWJY** [comment]
//demo
vector protect(int M /*รับค่าจากฟังก์ชัน steal*/ ){
  
  for( int i = 0; i < mycard.size ; i++){
    if(  M == /*การ์ดในมือ 5 ใบ*/ ){
        mycard.erase(i); //ลงไพ่เพื่อป้องกัน
    }
    else{
        //เรียกใช้ฟังก์ชัน allow()   
    }
    
    }  
    
}

**Comment by JWJY** [comment]
#include <vector>
#include <iostream>
using namespace std;

vector<int> mycard = {10000,50000,25000,20000,15000};

int protect(int M){
    for(unsigned int k = 0; k < 5 ; k++){
        cout << "["<< k+1 << "] " << mycard[k]<< '\n';
    }
    int b;
    int choose;
    cin >> choose;
        
            if(M <= mycard[choose-1]){
                b = choose;
                mycard.erase(mycard.begin()+choose-1);
            }
       

    for(unsigned int j = 0; j < 4 ; j++){
        cout << mycard[j]<< '\n';
    }
}


int main(){
    protect(5000);

}

**Comment by mon9k0rn** [comment]
for(unsigned int k = 0; k < p.hand.size() ; k++){
    cout << "["<< k+1 << "] " << p.hand[k].money<< '\n';
    }

    int choose;
    cin >> choose;//chooseเป็นตำแหน่งไม่ใช่จำนวนเงิน
        
        if(p.hand[choose-1]==mid.end()){
            mid.push_back(p.hand[choose-1]);
            p.hand.erase(p.hand.begin()+choose-1);
       }else if(p.hand[choose-1] == 25000){
            mid.push_back(p.hand[choose-1]);
            p.hand.erase(p.hand.begin()+choose-1);
       }else if(p.hand.[choose-1] == 50000){
            mid.push_back(p.hand[choose-1]);
            p.hand.erase(p.hand.begin()+choose-1);
        }

    for(unsigned int j = 0; j < p.hand.size() ; j++){
        cout << "["<< j+1 << "] " <<  p.hand[j].money << '\n';
    }
}
