### ISSUE TITLE
code-ขโมยการ์ดผู้เล่นคนอื่น

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/project#13]

**Comment by tensept** [comment]
int stealCard(int n){
    //choose card
    for(unsigned int i = 0; i < mycard.size(); i++){
        if(n == mycard[i]){
            a = mycard[i];
            mycard.erase(mycard.begin()+i);
        }
    }
    return a;    
}

**Comment by mon9k0rn** [comment]
#include <vector>
#include <iostream>
using namespace std;

vector<int> mycard = {10000,50000,25000,20000,15000};

int protect(int M){
    for(unsigned int k = 0; k < 5 ; k++){
        cout << "["<< k+1 << "] " << mycard[k]<< '\n';
    }
    int b;
    int choose;
    cin >> choose;
        
            if(M <= mycard[choose-1]){
                b = choose;
                mycard.erase(mycard.begin()+choose-1);
            }
       

    for(unsigned int j = 0; j < 4 ; j++){
        cout << mycard[j]<< '\n';
    }
}


int main(){
    protect(5000);

}

**Comment by mon9k0rn** [comment]
void stealCard(Player &b, Player &p,vector<Card> mid){
  //เช็คการ์ดบนมือ เท่ากับ mycard อีกฝั่ง
  for (int i = 0; i < p.hand.size(); i++)
  {
    if (b.mycard[mycard.size()-1].money==p.hand[i].money)
    {
      mid.push_back(p.hand[i]);
      p.hand.erase(p.hand.begin()+i);
      mid.push_back(b.mycard[sizeof(mycard)-1]);
      b.mycard.pop_back();
      mid.push_back(b.mycard[sizeof(mycard)-1]);
      b.mycard.pop_back();
    }
    //mid <3ค่า>
   // p1.stealCard(b,p1);
    
  }

**Comment by mon9k0rn** [comment]
void stealCard(Player &b, Player &p,vector<Card> mid){
  //เช็คการ์ดบนมือ เท่ากับ mycard อีกฝั่ง
  for (int i = 0; i < p.hand.size(); i++)
  {
    if (b.mycard[mycard.size()-1].money==p.hand[i].money)
    {
      mid.push_back(p.hand[i]);
      p.hand.erase(p.hand.begin()+i);
      mid.push_back(b.mycard[sizeof(mycard)-1]);
      b.mycard.pop_back();
      mid.push_back(b.mycard[sizeof(mycard)-1]);
      b.mycard.pop_back();
    }
    //mid <3ค่า>
   // p1.stealCard(b,p1);
    
  }

**Comment by mon9k0rn** [comment]
void stealCard(Player &b, Player &p,vector<Card> &mid,bool &s){
  for (int i = 0; i < p.hand.size(); i++)
  {
    if (b.mycard[b.mycard.size()-1].money==p.hand[i].money)
    {
      mid.push_back(p.hand[i]);
      //cout << mid[i].money << endl;
      mid.push_back(p.hand[i]);
     // cout << mid[i].money;
      mid.push_back(p.hand[i]);
      p.hand.erase(p.hand.begin()+i);
      b.mycard.pop_back();
       b.mycard.pop_back();
      s = true;
    }
    
  }
}

void botstealCard(Player &b, Player &p,vector<Card> mid,bool &s){
  for (int i = 0; i < p.hand.size(); i++)
  {
    if (p.mycard[mycard.size()-1].money==b.hand[i].money)
    {
      mid.push_back(b.hand[i]);
      b.hand.erase(b.hand.begin()+i);
      mid.push_back(p.mycard[sizeof(mycard)-1]);
      p.mycard.pop_back();
      mid.push_back(p.mycard[sizeof(mycard)-1]);
      p.mycard.pop_back();
      s =1;
    }
    
  }
}
