### ISSUE TITLE
ความคืบหน้าเรื่องการออกแบบหน้าตาเกม

### ISSUE THREAD

**Issue by ThanichaMongkorn** [ThanichaMongkorn/project#3]

**Comment by JWJY** [comment]
ไพ่
![8695F3FB-4A0B-4EE8-8E0E-21E437450FD7](https://user-images.githubusercontent.com/110969308/219950666-0438a02a-4e7f-4037-8ff6-39460779378a.jpeg)
![0E614186-175E-4F4D-95F1-06848A67C7A1](https://user-images.githubusercontent.com/110969308/219950674-5f8fed66-a6a8-4bb8-a30c-7d3c0a8048d2.jpeg)
![EA7355AD-EB3A-452D-8464-A25903DC96A6](https://user-images.githubusercontent.com/110969308/219950676-561025ce-551f-470f-a243-f2c4a27bbf81.jpeg)
![E721B8C2-05C4-4D6C-AB16-5826CB98703F](https://user-images.githubusercontent.com/110969308/219950680-0c54a25a-e11d-449c-b37c-b6f69af42d80.jpeg)

**Comment by JWJY** [comment]
![IMG_6755](https://user-images.githubusercontent.com/110969308/219950856-5b591aca-458a-4d3a-85f5-38d3b83884a9.jpeg)
![IMG_6756](https://user-images.githubusercontent.com/110969308/219950859-6a891646-adae-4caf-8157-0c2577dddf57.jpeg)

**Comment by ThanichaMongkorn** [comment]
เพื่อนๆโอเคกันม้ายยมีตรงไหนอยากให้เพิ่มอีกมั้ยยยย
@thanabordeee @wasiree @tensept

**Comment by tensept** [comment]
Okkk

**Comment by wasiree** [comment]
ไม่มี พิกกี้บูบู้แล้วหรอ55555

**Comment by ThanichaMongkorn** [comment]
@wasiree  น้องกลับไปอยู่ที่ฟาร์มแล้ว55555555

**Comment by JWJY** [comment]
หลังไพ่
![IMG_0730](https://user-images.githubusercontent.com/110969308/220010153-2819f4e7-532a-46d7-bfdc-c66be2c54c33.jpeg)

**Comment by JWJY** [comment]
วิธีการเล่นเกม
![IMG_0744](https://user-images.githubusercontent.com/110969308/221882092-28ed8259-830b-439a-9a67-6f34d68aa985.jpeg)

**Comment by JWJY** [comment]
พื้นหลังเกม
![IMG_0745](https://user-images.githubusercontent.com/110969308/222170899-5f7c3fbf-2cab-46fa-9216-394015a99aac.jpeg)

ตัวเลือก
![IMG_0736](https://user-images.githubusercontent.com/110969308/222171133-0c43859f-7cae-4f65-b0a6-73003798a23b.j
![IMG_0731](https://user-images.githubusercontent.com/110969308/222171300-45f9eee1-fa03-4a8f-894b-7972c4095ba9.jpeg)
peg)

**Comment by ThanichaMongkorn** [comment]
![image](https://user-images.githubusercontent.com/110970224/222332953-60bd4683-fdc0-47b5-b9b1-190c3b8ca0da.jpeg)

**Comment by ThanichaMongkorn** [comment]
![image](https://user-images.githubusercontent.com/110970224/222333071-a1407fe6-f9d0-46e7-8060-99af133eb09f.png)
