### ISSUE TITLE
code-draw+drop

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/project#5]

**Comment by thanabordeee** [comment]
draw + drop card(demo)
#include <iostream>
#include <ctime>
#include <cstdlib>
using namespace std;
void deckShuffle(int *);
void draw(int[][6], int *);
string money[] = {"5k","10k","15k","20k","25k","50k"};
string color[] = {"P","SK","PP","G","SV","GL"} ;
int main()
{
 char x;
 string y;
 int deck[6][6] = {};
 int count = 1;
 srand(time(0));
 deckShuffle(&deck[0][0]);
 cout << "do you want to draw ?(y = yes & n = no)  :";
 cin >> x;
 if (x == 'y')
 {
    draw(deck,&count);
 }
 else
 {
    if (x == 'n')
    {
       cout << "You didn't draw";
    }
    else
    {
      cout << "please input y or no";
    }
 }
 cout << "You have 6 cards drop 1 of your cards"<<endl;
 cout << "Choose 1 to drop : ";
 cin >> y;
 cout << "You drop " << y << endl;

 
 

 return 0;

}
void deckShuffle(int *dptr)
{
  int row,col;
  for (int i = 1; i <= 36; i++)
  {
    do
    {
        row = rand()%6;
        col = rand()%6;
    } while (*(dptr+col+6*row)!=0);
    *(dptr+col+6*row) = i;
  }
  
}
void draw(int d[][6],int *c)
{
    for (int i = 0; i < 6; i++)
    {
       for (int j = 0; j < 6; j++)
       {
        if (d[i][j] == *c)
        {
            cout << "You got " << money[i] << color[j] << endl;
            (*c)++;
            return;
        }
        
       }
       
    }
    
}

**Comment by thanabordeee** [comment]
![image](https://user-images.githubusercontent.com/110457187/222405272-ea5e3a75-f4d3-4b97-b31d-cf2bbe167040.png)


![image](https://user-images.githubusercontent.com/110457187/222405400-ad51f5d5-b435-4e30-9f5b-793565d1a6d1.png)


![image](https://user-images.githubusercontent.com/110457187/222405549-b74e357a-9550-421d-b71c-f59b4aa83089.png)


![image](https://user-images.githubusercontent.com/110457187/222405948-d79622fb-6646-4e7d-bbc2-3b625e361e0f.png)

**Comment by thanabordeee** [comment]
![image](https://user-images.githubusercontent.com/110457187/222406114-caa7aa8d-87cd-4251-b1e2-0bf2bb21e66c.png)

**Comment by thanabordeee** [comment]
draw + drop card(demo) edit**
#include <iostream>
#include <ctime>
#include <cstdlib>
using namespace std;
void deckShuffle(int *);
void draw(int[][6], int *);
string money[] = {"5k","10k","15k","20k","25k","50k"};
string color[] = {"P","SK","PP","G","SV","GL"} ;
int main()
{
 char x;
 string y;
 int deck[6][6] = {};
 int count = 1;
 srand(time(0));
 deckShuffle(&deck[0][0]);
 cout << "do you want to draw ?(y = yes & n = no)  :";
 cin >> x;
 if (x == 'y')
 {
    draw(deck,&count);
    cout << "You have 6 cards drop 1 of your cards"<<endl;
    cout << "Choose 1 to drop : ";
    cin >> y;
    cout << "You drop " << y << endl;
 }
 else
 {
    if (x == 'n')
    {
       cout << "You didn't draw";
    }
    else
    {
      cout << "please input y or n";
    }
 }
 

 
 

 return 0;

}
void deckShuffle(int *dptr)
{
  int row,col;
  for (int i = 1; i <= 36; i++)
  {
    do
    {
        row = rand()%6;
        col = rand()%6;
    } while (*(dptr+col+6*row)!=0);
    *(dptr+col+6*row) = i;
  }
  
}
void draw(int d[][6],int *c)
{
    for (int i = 0; i < 6; i++)
    {
       for (int j = 0; j < 6; j++)
       {
        if (d[i][j] == *c)
        {
            cout << "You got " << money[i] << color[j] << endl;
            (*c)++;
            return;
        }
        
       }
       
    }
    
}

**Comment by thanabordeee** [comment]
//update draw and drop demo v1.2
//add class card & class deck
//adjust all code
#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <ctime>

using namespace std;

//สร้าง Class ไว้เก็บ cards money + color
class Card {
public:
    string color;
    int money;
    Card(string, int);
   
};
Card::Card(string c, int m )
{
    color = c;
    money = m;
}

// สร้าง Deck มาเก็บ การ์ดแต่ละใบ
class Deck {
    public:
       vector<Card> cards;
       Deck();
       void shuffle()
              {
              // ฟังก์ชั้นสับไพ่
              random_shuffle(cards.begin(), cards.end());
              }
              //ฟังกฺชั่นโชว์ไพ่
       void ShowAllCards() 
              {
              for (int i = 0; i < cards.size(); i++) 
                {
                cout << cards[i].money << " " << cards[i].color << endl;
                }
              }  
};


Deck::Deck() {
        // สร้างการ์ด เงิน แต่ละสี อย่างละ 10 ใบ
        for (int i = 0; i < 10; i++) {
            cards.push_back(Card("Pink", 5000));
            cards.push_back(Card("Sky", 10000));
            cards.push_back(Card("Purple", 15000));
            cards.push_back(Card("Green", 20000));
        }
        // สร้างการ์ดเงิน 6 ใบ
        for (int i = 0; i < 6; i++) {
            cards.push_back(Card("Silver", 25000));
        } //สร้างการ์ดทอง 4 ใบ
        for (int i = 0; i < 4; i++) {
            cards.push_back(Card("Gold", 50000));
        }
    }

 class Player {
     public:
     vector<Card> hand;
     void draw(Deck &d)
     {
       //จั่วการ์ดจาก deck ขึ้นมือ pushไพ่ใบสุดท้ายจาก deck ขึ้นมือ
       hand.push_back(d.cards.back());
       //เอาไพ่ใบสุดท้ายจาก deck ออก
       d.cards.pop_back();
     }
     //ฟังก์ชั่น drop card demo(ยังดรอปแบบทิ้งไปเลยอยู่)
     void drop()
     {
        cout << "Your hand:" << endl;
        for (int i = 0; i < hand.size() ; i++)
        {
            cout << "["<< i+1 <<"]" << hand[i].money << " " << hand[i].color << endl; 
        }
        int select;
        cout << "Select number u want to drop. 1 -  " << hand.size()<< endl;
        cin >> select;
        // เงื่อนไข ถ้า ถ้าจำนวนที่เลือกไม่ตรงกับไพ่ที่มี ไม่ให้ดรอป
        if (select < 1 || select > hand.size())
        {
           cout << "incorrect please input number correctly. 1 - " << hand.size() <<endl;
           drop();
           return;
        }
        //ลบไพ่บนมือใบที่เลือกออก
        hand.erase(hand.begin() + select -1);
        
     }

 };




    int main()
    {   
        //สร้าง Deck d เพื่อนเรียกใช้ class Deck
        Deck d;
        //สร้าง Player p1 เพื่อเรียกใช้ class player
        Player p1;
        //สับไพ่
        d.shuffle();
        //จั่วไพ่5ใบ
        for (int i = 0; i < 5; i++)
        {
           p1.draw(d);
           
        }
        //คำสั่งโชว์ไพ่ + ให้เลือก draw drop
        while (true)
        {
          //โชว์ไพ่
          cout << "Your hand:" << endl;
          for (int i = 0; i < p1.hand.size(); i++) 
            {
              cout << "["<< i+1 <<"]" << p1.hand[i].money << " " << p1.hand[i].color << endl; 
            }
          string b;
          //ถามว่าจะ draw ไหม
          cout << "do you want to draw?(y or n)"<< endl;
          cin >> b;
          //ถ้าdraw 
          if (b == "y")
           {
            p1.draw(d);
            //ไพ่เกิน 5 ใบ ให้เลือก drop
            if (p1.hand.size() > 5)
            {
                cout << "you have 6 cards drop 1 of your cards"<<endl;
                p1.drop();
            }
            
           }
          //ถ้าไม่ draw
          else if (b == "n")
          {
            //จบคำสั่ง
            break;
          }
          //ถ้าใส่คำสั่งไม่ถูก
          else
          {
            cout << "Please input y or n"<< endl ;
          }
         
         
        }
    }

**Comment by thanabordeee** [comment]
//ตัวอย่าง
![image](https://user-images.githubusercontent.com/110457187/223908759-d8479026-212b-46e6-8f97-e81af3e69b17.png)

**Comment by thanabordeee** [comment]
//เลือกที่จะ draw
![image](https://user-images.githubusercontent.com/110457187/223908840-caaed343-fb9a-4fa8-826d-f50a5a5ce397.png)

**Comment by thanabordeee** [comment]
//เลือกเลขที่ถูกต้อง
![image](https://user-images.githubusercontent.com/110457187/223908956-927454ec-ce28-4c53-bfaa-bde2b3b20ad8.png)
//เลือกเลขที่ไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/110457187/223909222-84397b80-1aba-459c-9d8d-925d0f470305.png)

![image](https://user-images.githubusercontent.com/110457187/223909325-a557d96e-304c-44e6-aff1-307b3223c05c.png)

**Comment by thanabordeee** [comment]
เลือกที่จะไม่ draw
![image](https://user-images.githubusercontent.com/110457187/223909029-2f8c1b9b-3a4e-4bb9-8339-c35c7bf30fa5.png)

**Comment by thanabordeee** [comment]
//ใส่คำสั่งไม่ถูก
![image](https://user-images.githubusercontent.com/110457187/223909122-8ccd3150-2844-400e-9162-63d710b026e0.png)
