### ISSUE TITLE
code-คิดคะแนน

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/project#6]

**Comment by mon9k0rn** [comment]
เมื่อผู้เล่นจับคู่ไพ่และเก็บค่าไว้ตลอดจนจบเกมและสร้างfunction ที่นำค่ามารวมคะแนนและรับค่าจากfunctionจับคู่

**Comment by wasiree** [comment]
#include <iostream>
#include <vector>
using namespace std;

// ฟังก์ชันจับคู่ไพ่
void matchingcard(vector<int>& card, int x, int y) {
    if (card[x] == card[y]) { 
        card.erase(card.begin() + y); 
        card.erase(card.begin() + x); 
        // เรียกฟังก์ชัน draw_card เพื่อวาดไพ่ใหม่
        draw_card();
    } else { // กรณีไพ่สองใบไม่เหมือนกัน
        // เรียกฟังก์ชัน drop_card เพื่อลดคะแนน
        drop_card();
        // เรียกฟังก์ชัน draw_card เพื่อวาดไพ่ใหม่
        draw_card();
    }
}

int main() {
    vector<int> card = {20000, 5000, 10000, 5000, 15000};
    int x = 1;
    int y = 3;

    // เรียกใช้ฟังก์ชัน matchingcard เพื่อจับคู่ไพ่
    matchingcard(card, x, y);

    return 0;
}

//ฟังก์ชันรับค่าไพ่ที่จับคู่

**Comment by wasiree** [comment]
#include <iostream>
#include <vector>
using namespace std;


// ฟังก์ชันนับคะแนนรวมจากการจับคู่ไพ่
int total_score(vector<int> cards) {
    int sum = 0;
    for (int i = 0; i < cards.size() - 1; i += 2) {
        int score =  // เรียกใช้ฟังก์ชันจับคู่ไพ่
        sum += score;
    }
    return sum;
}

int main() {
    vector<int> cards = {5, 5, 10, 7, 3, 3, 6, 9};

    // เรียกใช้ฟังก์ชัน total_score เพื่อนับคะแนนรวมจากการจับคู่ไพ่
    int score = total_score(cards);

    cout << "total score =  " << score << endl;
    return 0;
}

// ฟังก์ชันรวมคะแนน (ยังไม่สมบูรณ์100%)

**Comment by mon9k0rn** [comment]
void total_score(Player &a, Player &b) {
	int sum_p = 0;
	int sum_b = 0;
		for (int i = 0; i < a.mycard.size(); i++) {
 
		sum_p += a.mycard[i].money;
		}
		
		for (int j = 0; j < b.mycard.size(); j++) {

		sum_b += b.mycard[j].money;
		}
		if(sum_p>sum_b) cout << "You wins" << sum_p;
	    else "You lose";
	
}
