### ISSUE TITLE
code-จับคู่การ์ด

### ISSUE THREAD

**Issue by mon9k0rn** [ThanichaMongkorn/project#7]

**Comment by tensept** [comment]
void matchingcard(vector<int> &callcard){
    //vector<int> card = {20000,5000,10000,5000,15000}
    //click card
    if(card[x] == card[y]){
        card.erase(x)
        card.erase(y)
        //draw card function
    }
    else //drop card function & draw card function
    
}

**Comment by mon9k0rn** [comment]
vector<Card> match_card(int s1, int s2){
        if(hand[s1-1].money==hand[s2-1].money){
            mycard.push_back(hand[s1-1]);
            mycard.push_back(hand[s2-1]);
        }

   hand.erase(hand.begin()+s1-1);
   hand.erase(hand.begin()+s2-1);

    return mycard;
}
vector<Card> botmatch_card(int s1, int s2){
        if(hand[s1].money==hand[s2].money){
            mycard.push_back(hand[s1]);
            mycard.push_back(hand[s2]);
        }

   hand.erase(hand.begin()+s1);
   hand.erase(hand.begin()+s2);

    return mycard;
}
